### ISSUE TITLE
PW-KDF is bad

### ISSUE THREAD

**Issue by Sc00bz** [agix/secretin#1]
Use PBKDF2, scrypt, or Argon2 as your password key derivation function instead of unsalted SHA256. Also you can use the username and site's domain as the salt.

**Comment by agix** [comment]
PBKDF2 is supported by w3c http://www.w3.org/TR/WebCryptoAPI/#pbkdf2 so I'll change it (@veorq agree on this too :D)

About the salt, if you use the site's domain DB is unexportable (or it's harder), and I can use the username as salt but I don't know if it's stronger to bruteforce than without but I can add this.

**Comment by Sc00bz** [comment]
You can remove the site's domain on export by doing the equivalent to a password change. Obviously when you do this you should create a random salt and store it with the offline data.

**Comment by agix** [comment]
Okay, sounds a good idea (erk I have to code it now :p )

**Comment by agix** [comment]
Mmh unfortunately pbkdf2 seems unsupported at the moment on the last chrome version (45.0.2454.101)

Trying to reproduce https://src.chromium.org/viewvc/blink/trunk/LayoutTests/crypto/subtle/pbkdf2/deriveKey-aes.html?revision=190912

In your console on https website.

```
var password = new Uint8Array(32);
crypto.getRandomValues(password);
var algorithm = {name: 'PBKDF2'};
var extractable = false;
var usages = ['deriveBits', 'deriveKey'];
crypto.subtle.importKey('raw', password, algorithm, extractable, usages)

Uncaught (in promise) DOMException: The requested operation is unsupported
```

importKey seems to work on firefox but deriveKey trigger error.

https://github.com/agix/secretin/blob/better_crypto/app/scripts/lib/crypto.js#L142

**Comment by agix** [comment]
https://github.com/agix/secretin/tree/waiting_for branch use 10 000 SHA256 on salted password waiting for PBKDF2 implementation.

**Comment by agix** [comment]
PBKDF2 works on recent chrome 46 so it's landed in master.
